import sqlite3 

cards = [
    {"question": "What is your name?", "answer": "Qual é o seu nome?", "theme_id": 3, "category_id": 1},
    {"question": "How are you?", "answer": "Como você está?", "theme_id": 3, "category_id": 1},
    {"question": "Where do you live?", "answer": "Onde você mora?", "theme_id": 3, "category_id": 1},
    {"question": "What time is it?", "answer": "Que horas são?", "theme_id": 3, "category_id": 1},
    {"question": "Can you help me?", "answer": "Você pode me ajudar?", "theme_id": 3, "category_id": 1},
    {"question": "Do you like music?", "answer": "Você gosta de música?", "theme_id": 3, "category_id": 1},
    {"question": "Where are you from?", "answer": "De onde você é?", "theme_id": 3, "category_id": 1},
    {"question": "What do you do?", "answer": "O que você faz?", "theme_id": 3, "category_id": 1},
    {"question": "How old are you?", "answer": "Quantos anos você tem?", "theme_id": 3, "category_id": 1},
    {"question": "Can I ask you something?", "answer": "Posso te perguntar algo?", "theme_id": 3, "category_id": 1},
    {"question": "Do you speak English?", "answer": "Você fala inglês?", "theme_id": 3, "category_id": 1},
    {"question": "What is your favorite food?", "answer": "Qual é sua comida favorita?", "theme_id": 3, "category_id": 1},
    {"question": "Where is the nearest hospital?", "answer": "Onde fica o hospital mais próximo?", "theme_id": 3, "category_id": 1},
    {"question": "Do you know where I am?", "answer": "Você sabe onde estou?", "theme_id": 3, "category_id": 1},
    {"question": "What is the weather like?", "answer": "Como está o tempo?", "theme_id": 3, "category_id": 1},
    {"question": "What is your phone number?", "answer": "Qual é o seu número de telefone?", "theme_id": 3, "category_id": 1},
    {"question": "Can you repeat that?", "answer": "Você pode repetir isso?", "theme_id": 3, "category_id": 1},
    {"question": "What is this called?", "answer": "Como se chama isso?", "theme_id": 3, "category_id": 1},
    {"question": "Do you like sports?", "answer": "Você gosta de esportes?", "theme_id": 3, "category_id": 1},
    {"question": "Where can I find coffee?", "answer": "Onde posso encontrar café?", "theme_id": 3, "category_id": 1},
    {"question": "What is your favorite movie?", "answer": "Qual é o seu filme favorito?", "theme_id": 3, "category_id": 1},
    {"question": "Do you have a pet?", "answer": "Você tem um animal de estimação?", "theme_id": 3, "category_id": 1},
    {"question": "Can I borrow your pen?", "answer": "Posso pegar sua caneta emprestada?", "theme_id": 3, "category_id": 1},
    {"question": "What day is it today?", "answer": "Que dia é hoje?", "theme_id": 3, "category_id": 1},
    {"question": "Where is the restroom?", "answer": "Onde fica o banheiro?", "theme_id": 3, "category_id": 1},
    {"question": "What is your favorite book?", "answer": "Qual é o seu livro favorito?", "theme_id": 3, "category_id": 1},
    {"question": "How much does it cost?", "answer": "Quanto custa isso?", "theme_id": 3, "category_id": 1},
    {"question": "Do you need anything?", "answer": "Você precisa de alguma coisa?", "theme_id": 3, "category_id": 1},
    {"question": "What are you doing now?", "answer": "O que você está fazendo agora?", "theme_id": 3, "category_id": 1},
    {"question": "Can I sit here?", "answer": "Posso sentar aqui?", "theme_id": 3, "category_id": 1},
    {"question": "Where is the bus stop?", "answer": "Onde fica o ponto de ônibus?", "theme_id": 3, "category_id": 1},
    {"question": "Do you have siblings?", "answer": "Você tem irmãos?", "theme_id": 3, "category_id": 1},
    {"question": "What do you think?", "answer": "O que você acha?", "theme_id": 3, "category_id": 1},
    {"question": "Can I use your phone?", "answer": "Posso usar seu telefone?", "theme_id": 3, "category_id": 1},
    {"question": "What do you like to do?", "answer": "O que você gosta de fazer?", "theme_id": 3, "category_id": 1},
    {"question": "Are you feeling better now?", "answer": "Você está se sentindo melhor agora?", "theme_id": 3, "category_id": 1},
    {"question": "Where did you buy this?", "answer": "Onde você comprou isso?", "theme_id": 3, "category_id": 1},
    {"question": "What is your dream job?", "answer": "Qual é o seu trabalho dos sonhos?", "theme_id": 3, "category_id": 1},
    {"question": "Are you ready to leave?", "answer": "Você está pronto para sair?", "theme_id": 3, "category_id": 1},
    {"question": "Where should we meet?", "answer": "Onde devemos nos encontrar?", "theme_id": 3, "category_id": 1},
    {"question": "Do you want to go out?", "answer": "Você quer sair?", "theme_id": 3, "category_id": 1},
    {"question": "When is your birthday?", "answer": "Quando é o seu aniversário?", "theme_id": 3, "category_id": 1},
    {"question": "Do you like Brazilian food?", "answer": "Você gosta de comida brasileira?", "theme_id": 3, "category_id": 1},
    {"question": "What do you study?", "answer": "O que você estuda?", "theme_id": 3, "category_id": 1},
    {"question": "How do I get to the mall?", "answer": "Como eu chego ao shopping?", "theme_id": 3, "category_id": 1},
    {"question": "Can I get you a drink?", "answer": "Posso te oferecer uma bebida?", "theme_id": 3, "category_id": 1},
    {"question": "Do you know this person?", "answer": "Você conhece essa pessoa?", "theme_id": 3, "category_id": 1},
    {"question": "What is your favorite place?", "answer": "Qual é o seu lugar favorito?", "theme_id": 3, "category_id": 1},
    {"question": "Are you learning Portuguese?", "answer": "Você está aprendendo português?", "theme_id": 3, "category_id": 1},
    {"question": "How can I contact you?", "answer": "Como posso te contatar?", "theme_id": 3, "category_id": 1},
    {"question": "Are you free this weekend?", "answer": "Você está livre neste fim de semana?", "theme_id": 3, "category_id": 1},
    {"question": "Do you want some help?", "answer": "Você quer ajuda?", "theme_id": 3, "category_id": 1},
    {"question": "What is your favorite season?", "answer": "Qual é a sua estação favorita?", "theme_id": 3, "category_id": 1},
    {"question": "Do you work or study?", "answer": "Você trabalha ou estuda?", "theme_id": 3, "category_id": 1},
    {"question": "What music do you like?", "answer": "Que tipo de música você gosta?", "theme_id": 3, "category_id": 1},
    {"question": "Can you play an instrument?", "answer": "Você sabe tocar algum instrumento?", "theme_id": 3, "category_id": 1},
    {"question": "Are you hungry?", "answer": "Você está com fome?", "theme_id": 3, "category_id": 1},
    {"question": "What time do you wake up?", "answer": "Que horas você acorda?", "theme_id": 3, "category_id": 1},
    {"question": "Do you enjoy traveling?", "answer": "Você gosta de viajar?", "theme_id": 3, "category_id": 1},
    {"question": "Can you show me the way?", "answer": "Você pode me mostrar o caminho?", "theme_id": 3, "category_id": 1},
    {"question": "How do you spell that?", "answer": "Como se soletra isso?", "theme_id": 3, "category_id": 1},
    {"question": "Do you like reading books?", "answer": "Você gosta de ler livros?", "theme_id": 3, "category_id": 1},
    {"question": "Do you have free time?", "answer": "Você tem tempo livre?", "theme_id": 3, "category_id": 1},
    {"question": "What are your plans tomorrow?", "answer": "Quais são seus planos para amanhã?", "theme_id": 3, "category_id": 1},
    {"question": "Do you like your job?", "answer": "Você gosta do seu trabalho?", "theme_id": 3, "category_id": 1},
    {"question": "Where is your family from?", "answer": "De onde é sua família?", "theme_id": 3, "category_id": 1},
    {"question": "What is your daily routine?", "answer": "Qual é a sua rotina diária?", "theme_id": 3, "category_id": 1},
    {"question": "Can you speak slowly?", "answer": "Você pode falar devagar?", "theme_id": 3, "category_id": 1},
    {"question": "What is your dream vacation?", "answer": "Qual é sua viagem dos sonhos?", "theme_id": 3, "category_id": 1},
    {"question": "Do you enjoy cooking?", "answer": "Você gosta de cozinhar?", "theme_id": 3, "category_id": 1},
    {"question": "Where do you usually eat?", "answer": "Onde você costuma comer?", "theme_id": 3, "category_id": 1},
    {"question": "What language are you learning?", "answer": "Qual idioma você está aprendendo?", "theme_id": 3, "category_id": 1},
    {"question": "What is your favorite drink?", "answer": "Qual é a sua bebida favorita?", "theme_id": 3, "category_id": 1},
    {"question": "Do you prefer cats or dogs?", "answer": "Você prefere gatos ou cachorros?", "theme_id": 3, "category_id": 1},
    {"question": "Can I borrow your book?", "answer": "Posso pegar seu livro emprestado?", "theme_id": 3, "category_id": 1},
    {"question": "Are you a student?", "answer": "Você é estudante?", "theme_id": 3, "category_id": 1},
    {"question": "What time do you sleep?", "answer": "Que horas você dorme?", "theme_id": 3, "category_id": 1},
    {"question": "What is your email address?", "answer": "Qual é o seu endereço de email?", "theme_id": 3, "category_id": 1},
    {"question": "Where do you usually shop?", "answer": "Onde você costuma fazer compras?", "theme_id": 3, "category_id": 1},
    {"question": "Do you watch movies often?", "answer": "Você assiste filmes com frequência?", "theme_id": 3, "category_id": 1},
    {"question": "Can I ask for advice?", "answer": "Posso pedir um conselho?", "theme_id": 3, "category_id": 1},
    {"question": "What are your favorite hobbies?", "answer": "Quais são seus hobbies favoritos?", "theme_id": 3, "category_id": 1},
    {"question": "What do you do for fun?", "answer": "O que você faz para se divertir?", "theme_id": 3, "category_id": 1},
    {"question": "How do you get to work?", "answer": "Como você vai para o trabalho?", "theme_id": 3, "category_id": 1},
    {"question": "What’s the best place to visit?", "answer": "Qual é o melhor lugar para visitar?", "theme_id": 3, "category_id": 1},
    {"question": "What do you do on weekends?", "answer": "O que você faz nos finais de semana?", "theme_id": 3, "category_id": 1},
    {"question": "What do you want to eat?", "answer": "O que você quer comer?", "theme_id": 3, "category_id": 1}
  ]
conn = sqlite3.connect('db.db')
cursor = conn.cursor()

for i in range(len(cards)):
    cursor.execute("INSERT INTO cards (question, answer, theme_id, category_id) VALUES (?,?,?,?)", (cards[i]['question'], cards[i]['answer'], cards[i]['theme_id'], cards[i]['category_id']))

conn.commit()
